name: Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  # This simple deployment action is suitable for a basic deployment to a single remote server.
  # It is not appropriate for more complex deployment scenarios.
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          command_timeout: 60m
          script: |
            cd ${{ secrets.REMOTE_GIT_PATH }}
            git pull origin
            docker compose -f docker-compose-prod.yaml down
            docker compose -f docker-compose-prod.yaml build
            docker image prune --force
            docker compose -f docker-compose-prod.yaml up -d
